services:
  - type: web
    name: forex-bot
    env: python
    pythonVersion: 3.11  # <- downgrade qui
    plan: free
    region: oregon
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: ""
      - key: CHAT_ID
        value: ""
