services:
  - type: web
    name: forex-bot
    env: docker
    plan: free
    region: oregon
    # Non serve buildCommand/startCommand, Docker li gestisce
    envVars:
      - key: BOT_TOKEN
        value: ""
      - key: CHAT_ID
        value: ""
