services:
  - type: web
    name: forex-factory-bot
    env: python
    plan: free
    runtime: python3.11
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
